[package]
name = "cryptopals-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
structopt = { version = "0.3", default-features = false }
base64 = "0.21"                                           # Replace with the latest version
